# Este é o primeiro arquivo que o spring vai ler para buscar as configurações de qualquer biblioteca que tenha no projeto

server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # Comma-separated list of MIME types that should be compressed.
    min-response-size: 1024 # Minimum "Content-Length" value that is required for compression to be performed.
  undertow:
    threads:
      worker: 64 # Number of worker threads. The default is 8 times the number of I/O threads. Generally this should be reasonably high, at least 10 per CPU core: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2
      io: 4 # Number of I/O threads to create for the worker. The default is derived from the number of available processors.